/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IVeraKeyAccount  {
    function initialize(bytes32 app_id, bytes32 owner_nullifier, address verifier, address usdg, bytes32 rp_id_hash, bytes calldata origin, uint256 per_tx_cap, uint256 daily_cap, uint64 change_delay, uint64 recovery_delay) external;

    function pay(address to, uint256 amount, uint256 fee, uint64 deadline, bytes32 nullifier, bytes calldata client_data_json, bytes calldata proof) external;

    function scheduleChange(uint8 change_kind, bytes calldata payload, uint256 fee, uint64 deadline, bytes32 nullifier, bytes calldata client_data_json, bytes calldata proof) external returns (bytes32);

    function applyChange(bytes32 change_id, uint8 change_kind, bytes calldata payload) external;

    function cancelChange(bytes32 change_id, uint256 fee, uint64 deadline, bytes32 nullifier, bytes calldata client_data_json, bytes calldata proof) external;

    function guardianCancelChange(bytes32 change_id) external;

    function initiateRecovery(bytes32 new_nullifier) external;

    function executeRecovery() external;

    function cancelRecovery(uint256 fee, uint64 deadline, bytes32 nullifier, bytes calldata client_data_json, bytes calldata proof) external;

    function guardianCancelRecovery() external;

    function actionHash(uint8 action_kind, address target, uint256 amount, bytes32 data_hash, uint256 fee, uint64 deadline) external view returns (bytes32);

    function initialized() external view returns (bool);

    function nonce() external view returns (uint256);

    function appId() external view returns (bytes32);

    function isOwner(bytes32 nullifier) external view returns (bool);

    function ownerCount() external view returns (uint256);

    function ownerEpoch() external view returns (uint256);

    function policy() external view returns (uint256, uint256, uint256, uint64, bool);

    function isRecipientAllowed(address recipient) external view returns (bool);

    function guardian() external view returns (address);

    function recovery() external view returns (bytes32, uint64);

    function pendingChange(bytes32 change_id) external view returns (uint8, bytes32, uint64, uint256);

    function config() external view returns (address, address, address, bytes32, uint64, uint64);

    function origin() external view returns (bytes memory);

    error AlreadyInitialized();

    error NotInitialized();

    error InvalidConfig();

    error DeadlineExpired();

    error DeadlineTooFar();

    error NotOwner();

    error InvalidClientData(uint8);

    error InvalidProof();

    error InvalidAmount();

    error InvalidRecipient();

    error RecipientNotAllowed();

    error PerTxCapExceeded();

    error DailyCapExceeded();

    error InvalidChange();

    error UnknownChange();

    error ChangeNotReady(uint64);

    error NotGuardian();

    error NoRecovery();

    error RecoveryNotReady(uint64);

    error LastOwner();

    error AlreadyOwner();

    error TokenTransferFailed();
}
