/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IVeraKeyFactory  {
    function createAccount(bytes32 app_id, bytes32 nullifier) external returns (address);

    function accountAddress(bytes32 app_id, bytes32 nullifier) external view returns (address);

    function configHash() external view returns (bytes32);

    function config() external view returns (address, address, address, bytes32, uint256, uint256, uint256, uint64, uint64, address, uint256);

    function origin() external view returns (bytes memory);

    error InvalidConfig();

    error InvalidIdentifier();

    error DeploymentFailed();

    error InitializationFailed();
}
