import { formatUsdg } from "@/lib/format";
import { useVeraKey } from "@/state/VeraKeyProvider";
import sepolia from "../../../../../deployments/sepolia.json";
import { A, Address, Callout, Code, H2, Table } from "../../components";

const RPC = sepolia.rpcUrl;

const CONTRACTS: { key: keyof typeof sepolia.contracts; name: string; role: string }[] = [
  { key: "factory", name: "VeraKeyFactory", role: "Stylus. Creates every account at its CREATE2 address." },
  { key: "accountImplementation", name: "VeraKeyAccount", role: "Stylus. The implementation every account clones." },
  { key: "honkVerifier", name: "HonkVerifier", role: "Solidity, generated by bb. Verifies authorization proofs." },
  { key: "linkVerifier", name: "LinkHonkVerifier", role: "Solidity, generated by bb. Verifies disclosure proofs." },
  { key: "veraKeyValidator", name: "VeraKeyValidator", role: "Solidity. The ERC-7579 validator module." },
  { key: "usdg", name: "USDG", role: "Paxos Global Dollar, the token accounts hold and pay." },
];

const SOURCIFY = ["honkVerifier", "linkVerifier", "veraKeyValidator"] as const;

const usdg = (units: string) => `${formatUsdg(BigInt(units))} USDG`;
const minutes = (seconds: number) => (seconds % 60 === 0 ? `${seconds / 60} minutes` : `${seconds} seconds`);

function LiveNetwork() {
  const { config, configError } = useVeraKey();
  if (!config) {
    return configError ? (
      <Callout kind="note">
        The live configuration could not be loaded; the addresses above are the canonical Arbitrum Sepolia deployment.
      </Callout>
    ) : (
      <p>Loading the live configuration…</p>
    );
  }
  const canonical = config.contracts.factory.toLowerCase() === sepolia.contracts.factory.toLowerCase();
  return (
    <>
      <p>
        {canonical
          ? "This app uses the Arbitrum Sepolia deployment above. Its relayer reports:"
          : `This app runs on ${config.chainName} (chain ${config.chainId}) with its own contracts:`}
      </p>
      <Table
        head={["Setting", "Value"]}
        rows={[
          ["Network", `${config.chainName} (chain ${config.chainId})`],
          ["Origin and rpId", <code key="o">{`${config.origin} · ${config.rpId}`}</code>],
          ["Factory", <Address key="f" value={config.contracts.factory} explorer={config.explorerUrl} />],
          ["Relayer and fee recipient", <Address key="r" value={config.relayer.address} explorer={config.explorerUrl} />],
          ["Relayer fee, signed into every action", usdg(config.relayer.fee)],
          ["Demo faucet, per new account", usdg(config.relayer.faucetAmount)],
        ]}
      />
      <p>
        The same values come from <A href="/api/config">/api/config</A>; see the <A href="/docs/build/relayer-api">Relayer API</A>.
      </p>
    </>
  );
}

export default function DeploymentsPage() {
  return (
    <>
      <H2>Arbitrum Sepolia</H2>
      <p>
        Chain {sepolia.chainId}, deployed on {sepolia.deployedAt.slice(0, 10)} for the origin{" "}
        <code>{sepolia.origin}</code>.
      </p>
      <Table
        stack
        head={["Contract", "Address"]}
        rows={CONTRACTS.filter(c => sepolia.contracts[c.key]).map(c => [
          <span key="n"><strong>{c.name}</strong><br />{c.role}</span>,
          <Address key="a" value={sepolia.contracts[c.key]} />,
        ])}
      />
      <Table
        head={["Hash", "Value"]}
        rows={[
          ["rpIdHash", <code key="r">{sepolia.rpIdHash}</code>],
          ["configHash", <code key="c">{sepolia.configHash}</code>],
          ["Authorization circuit VK hash", <code key="v">{sepolia.circuitVkHash}</code>],
          ["Link circuit VK hash", <code key="l">{sepolia.linkCircuitVkHash}</code>],
        ]}
      />

      <H2>Policy for new accounts</H2>
      <p>Every account the factory creates starts with this policy. The owner can tighten it at once, or loosen it after the change delay.</p>
      <Table
        head={["Setting", "Value"]}
        rows={[
          ["Per-payment cap", usdg(sepolia.policy.perTxCap)],
          ["Daily cap", usdg(sepolia.policy.dailyCap)],
          ["New-recipient cap", usdg(sepolia.policy.newPayeeCap)],
          ["Largest fee per action (maxFee)", usdg(sepolia.policy.maxFee)],
          ["Fee recipient (the relayer)", <Address key="f" value={sepolia.policy.feeRecipient} />],
          ["Change delay", `${minutes(sepolia.policy.changeDelay)} (a demo value)`],
          ["Recovery delay", `${minutes(sepolia.policy.recoveryDelay)} (a demo value)`],
        ]}
      />
      <p>
        The fee recipient and <code>maxFee</code> are part of the configuration hash, so no account can pay its fees
        anywhere else. See <A href="/docs/build/policy">Payments and policy</A>.
      </p>

      <H2>This app's network</H2>
      <LiveNetwork />

      <H2>Verify the contracts</H2>
      <p>The Solidity contracts are source-verified on Sourcify (exact match):</p>
      <ul>
        {SOURCIFY.map(key => (
          <li key={key}>
            <A href={`https://repo.sourcify.dev/${sepolia.chainId}/${sepolia.contracts[key]}`}>
              {CONTRACTS.find(c => c.key === key)?.name}
            </A>
          </li>
        ))}
      </ul>
      <p>
        Sourcify does not verify Stylus programs. To check what an address runs, read it from the chain, for example with
        Foundry's <code>cast</code>:
      </p>
      <Code lang="bash" title="Read-only checks">{`
RPC=${RPC}

# The code hash of a deployed program, to compare or pin
cast codehash ${sepolia.contracts.accountImplementation} --rpc-url $RPC

# The factory's configuration hash: it must equal configHash above
cast call ${sepolia.contracts.factory} "configHash()(bytes32)" --rpc-url $RPC

# An account is an EIP-1167 clone of the implementation:
# 0x363d3d373d3d3d363d73 <implementation> 5af43d82803e903d91602b57fd5bf3
cast code <account> --rpc-url $RPC

# The factory, verifier, token, rpIdHash and delays an account uses
cast call <account> "config()(address,address,address,bytes32,uint64,uint64)" --rpc-url $RPC
`}</Code>
    </>
  );
}
