// Writes packages/sdk/src/abi.ts from forge artifacts. Events are declared in Rust with `sol!`,
// which `cargo stylus export-abi` does not export, so they are appended here.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const artifact = (file, name) =>
  JSON.parse(readFileSync(resolve(root, `contracts/evm/out/${file}/${name}.json`), "utf8")).abi;

const event = (name, inputs) => ({ type: "event", name, anonymous: false, inputs });
const p = (name, type, indexed = false) => ({ name, type, indexed });

const accountEvents = [
  event("Initialized", [p("appId", "bytes32", true), p("ownerNullifier", "bytes32", true), p("factory", "address")]),
  event("Paid", [p("nonce", "uint256", true), p("to", "address", true), p("amount", "uint256"), p("fee", "uint256"), p("submitter", "address", true)]),
  event("ChangeScheduled", [p("changeId", "bytes32", true), p("changeKind", "uint8"), p("payload", "bytes"), p("eta", "uint64")]),
  event("ChangeApplied", [p("changeId", "bytes32", true), p("changeKind", "uint8")]),
  event("ChangeCancelled", [p("changeId", "bytes32", true)]),
  event("Restricted", [p("restrictionId", "bytes32", true), p("changeKind", "uint8"), p("payload", "bytes")]),
  event("GuardianFroze", []),
  event("RecoveryInitiated", [p("newNullifier", "bytes32", true), p("eta", "uint64")]),
  event("RecoveryExecuted", [p("newNullifier", "bytes32", true), p("ownerEpoch", "uint256")]),
  event("RecoveryCancelled", [p("newNullifier", "bytes32", true)]),
];
const factoryEvents = [
  event("AccountCreated", [p("appId", "bytes32", true), p("nullifier", "bytes32", true), p("account", "address", true)]),
];

const out = `// GENERATED by scripts/gen-abi.sh from the Stylus contracts — do not edit by hand.
export const veraKeyAccountAbi = ${JSON.stringify([...artifact("IVeraKeyAccount.sol", "IVeraKeyAccount"), ...accountEvents], null, 2)} as const;

export const veraKeyFactoryAbi = ${JSON.stringify([...artifact("IVeraKeyFactory.sol", "IVeraKeyFactory"), ...factoryEvents], null, 2)} as const;

export const honkVerifierAbi = ${JSON.stringify(artifact("HonkVerifier.sol", "HonkVerifier").filter(i => i.type === "function" && i.name === "verify" || i.type === "error"), null, 2)} as const;

export const erc20Abi = [
  { type: "function", name: "balanceOf", stateMutability: "view", inputs: [{ name: "owner", type: "address" }], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "transfer", stateMutability: "nonpayable", inputs: [{ name: "to", type: "address" }, { name: "value", type: "uint256" }], outputs: [{ name: "", type: "bool" }] },
  { type: "function", name: "decimals", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint8" }] },
  { type: "event", name: "Transfer", anonymous: false, inputs: [{ name: "from", type: "address", indexed: true }, { name: "to", type: "address", indexed: true }, { name: "value", type: "uint256", indexed: false }] },
] as const;
`;
writeFileSync(resolve(root, "packages/sdk/src/abi.ts"), out);
console.log("wrote packages/sdk/src/abi.ts");
