import { A, Code, Flow, H2, Lanes, Table } from "../../components";

export default function OverviewPage() {
  return (
    <>
      <H2>Components</H2>
      <p>
        VeraKey has three places where code runs: your device, a relayer, and Arbitrum. Secrets stay on the device;
        the relayer only moves proofs; Arbitrum decides.
      </p>
      <Lanes
        lanes={[
          {
            title: "Your device",
            items: [
              { name: "Passkey provider", detail: "iCloud Keychain or Google Password Manager: holds the P-256 key, checks Face ID or Touch ID, returns the PRF secret." },
              { name: "VeraKey app and SDK", detail: "Builds action hashes, asks the passkey to sign, keeps the session." },
              { name: "Provers (bb.js)", detail: "Prove the authorization and link circuits with UltraHonk, in the browser." },
            ],
          },
          {
            title: "Relayer (server/)",
            items: [
              { name: "Relay API", detail: "Creates accounts; checks, simulates and submits proof-authorized calls; pays the gas." },
              { name: "RPC proxy", detail: "Read-only JSON-RPC for the browser; keeps provider keys server-side." },
              { name: "Demo faucet", detail: "Sends test USDG to new accounts." },
            ],
          },
          {
            title: "Arbitrum",
            items: [
              { name: "VeraKeyFactory (Stylus)", detail: "Creates each account as an EIP-1167 clone at a CREATE2 address." },
              { name: "VeraKeyAccount (Stylus)", detail: "Parses client data, calls the verifier, enforces the policy, pays in USDG." },
              { name: "HonkVerifier, LinkHonkVerifier", detail: "Solidity UltraHonk verifiers generated by bb from the circuits." },
              { name: "VeraKeyValidator", detail: "ERC-7579 module: the same proofs for modular accounts." },
              { name: "USDG", detail: "Paxos Global Dollar, the token every account holds and pays." },
            ],
          },
        ]}
      />

      <H2>A payment end to end</H2>
      <Flow
        steps={[
          { title: "Hash", detail: "The SDK computes the action hash from the chain, account, nonce, payment, fee and deadline." },
          { title: "Sign", detail: "The passkey signs it after user verification: a 37-byte authenticator data and a P-256 signature." },
          { title: "Prove", detail: "bb.js proves the signature, the flags, the rpId and the nullifier in about 2 s." },
          { title: "Relay", detail: "The relayer checks the account, simulates the call and submits it." },
          { title: "Settle", detail: "The account verifies, applies its policy, consumes the nonce and transfers USDG." },
        ]}
      />
      <p>What crosses each boundary:</p>
      <Table
        head={["From → to", "What is sent"]}
        rows={[
          ["Passkey → browser", "The assertion (signature, authenticator data, client data) and, when unlocking, the PRF secret."],
          ["Browser → relayer", "The account, the function and its arguments: amount, recipient, fee, deadline, nullifier, client data and the proof."],
          ["Relayer → Arbitrum", "The same call, as a transaction the relayer signs and pays for."],
          ["Account → verifier", "The proof and six public inputs: the client data hash, the rpId hash, the app id and the nullifier."],
        ]}
      />

      <H2>Trust boundaries</H2>
      <Table
        head={["Component", "Trusted for", "What limits it"]}
        rows={[
          ["The VeraKey page code", "Handling the passkey, the PRF secret and the signature in your browser", "Proving only in the browser, a strict CSP with no third-party scripts, a self-hosted CRS, an open-source client. Every action still needs a fresh passkey approval, and the caps, the new-recipient cap, the fee limit, the timelocks and, optionally, the payment sheet bound what an approved action can do."],
          ["The relayer", "Liveness, and it sees request metadata (IP, timing)", "It cannot move funds or change what was signed. Anyone can submit the same calldata; fees go only to the fixed fee recipient. Rate-limit keys are a daily-rotated HMAC of the IP, kept in memory."],
          ["The circuits and verifiers", "Soundness of the proofs", "Generated by Barretenberg 5.2.0 from Noir sources; not independently audited."],
          ["The USDG issuer", "The token itself", "Paxos can freeze any single account: VeraKey is unlinkable, not anonymous."],
          ["Browsers", "Serializing clientDataJSON as WebAuthn Level 3 specifies", "The account rejects client data whose first keys are not type, challenge and origin."],
        ]}
      />
      <p>
        The <A href="/docs/security">security model</A> lists every invariant with the test that checks it.
      </p>

      <H2>Repository layout</H2>
      <Code lang="text">{`
circuits/webauthn        Noir authorization circuit + tests
circuits/link            Noir consent-to-link circuit + tests
circuits/verakey_lib     the shared WebAuthn assertion check and nullifier
contracts/stylus         Rust: core (pure logic + property tests), account, factory
contracts/evm            Foundry: bb-generated verifiers, ERC-7579 validator + tests, deploy scripts, test token
packages/sdk             @verakey/sdk: WebAuthn/PRF/SPC, action hashing, provers, VeraKeyClient, disclosures, validator
server                   Express relayer: /api/config, /api/accounts, /api/relay, /api/faucet, /api/rpc
client                   Vite + React app: landing page, /app, /docs
scripts                  build-circuit.sh, gen-abi.sh, devnode.sh, deploy.sh, browser-e2e.mjs, check-docs.mjs
deployments              addresses per network
`}</Code>
    </>
  );
}
